# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [57]:
import pandas as pd
url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv'
df = pd.read_csv(url)

In [2]:
df.shape

(10910, 26)

In [3]:
df.columns

Index(['Unnamed: 0', 'Customer', 'State', 'Customer Lifetime Value',
       'Response', 'Coverage', 'Education', 'Effective To Date',
       'EmploymentStatus', 'Gender', 'Income', 'Location Code',
       'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim',
       'Months Since Policy Inception', 'Number of Open Complaints',
       'Number of Policies', 'Policy Type', 'Policy', 'Renew Offer Type',
       'Sales Channel', 'Total Claim Amount', 'Vehicle Class', 'Vehicle Size',
       'Vehicle Type'],
      dtype='object')

In [4]:
df.dtypes

Unnamed: 0                         int64
Customer                          object
State                             object
Customer Lifetime Value          float64
Response                          object
Coverage                          object
Education                         object
Effective To Date                 object
EmploymentStatus                  object
Gender                            object
Income                             int64
Location Code                     object
Marital Status                    object
Monthly Premium Auto               int64
Months Since Last Claim          float64
Months Since Policy Inception      int64
Number of Open Complaints        float64
Number of Policies                 int64
Policy Type                       object
Policy                            object
Renew Offer Type                  object
Sales Channel                     object
Total Claim Amount               float64
Vehicle Class                     object
Vehicle Size                      object
Vehicle Type                      object
dtype: object

In [5]:
df["Total Claim Amount"].value_counts().sort_index()

Total Claim Amount
0.099007       1
0.382107       2
0.423310       2
0.517753       1
0.769185       2
              ..
2345.413441    1
2452.894264    1
2552.343856    2
2759.794354    1
2893.239678    1
Name: count, Length: 5106, dtype: int64

In [6]:
def lower_total_claim_amount(x): 
    if x <= 1000:
        return "lower"
    else:
        return "other"

In [7]:
df["lower_total_claim_amount"] = df["Total Claim Amount"].apply(lower_total_claim_amount)

In [8]:
df.groupby("lower_total_claim_amount")["Response"].value_counts()

lower_total_claim_amount  Response
lower                     No          8414
                          Yes         1399
other                     No           399
                          Yes           67
Name: count, dtype: int64

In [9]:
df2 = df[(df["Response"] == "Yes") & (df["lower_total_claim_amount"] == "lower")]

In [10]:
df2.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type,lower_total_claim_amount
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,lower
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN,lower
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN,lower
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A,lower
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN,lower

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [52]:
df.groupby(['Policy Type', "Gender"])['Monthly Premium Auto'].mean()

Policy Type     Gender
Corporate Auto  F         91.384615
                M         94.764249
Personal Auto   F         93.153179
                M         93.301056
Special Auto    F         93.563025
                M         93.197044
Name: Monthly Premium Auto, dtype: float64

In [53]:
df.groupby(['Policy Type', "Gender"])['Total Claim Amount'].mean()

Policy Type     Gender
Corporate Auto  F         397.799287
                M         462.223565
Personal Auto   F         413.239658
                M         459.919476
Special Auto    F         458.139623
                M         420.355202
Name: Total Claim Amount, dtype: float64

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [62]:
df.groupby(["State", "Response"])['Customer'].count()

State       Response
Arizona     No          1656
            Yes          281
California  No          3048
            Yes          504
Nevada      No           853
            Yes          140
Oregon      No          2490
            Yes          419
Washington  No           766
            Yes          122
Name: Customer, dtype: int64

In [63]:
df.groupby(["State", "Response"])["Customer"].count().loc[lambda x: x > 500]

State       Response
Arizona     No          1656
California  No          3048
            Yes          504
Nevada      No           853
Oregon      No          2490
Washington  No           766
Name: Customer, dtype: int64

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [64]:
df.groupby(["Gender", "Education" ])['Customer Lifetime Value'].agg(['max', 'mean', 'median'])

                                     max         mean       median
Gender Education
F      Bachelor              73225.95652  7874.269478  5640.505303
       College               61850.18803  7748.823325  5623.611187
       Doctor                44856.11397  7328.508916  5332.462694
       High School or Below  55277.44589  8675.220201  6039.553187
       Master                51016.06704  8157.053154  5729.855012
M      Bachelor              67907.27050  7703.601675  5548.031892
       College               61134.68307  8052.459288  6005.847375
       Doctor                32677.34284  7415.333638  5577.669457
       High School or Below  83325.38119  8149.687783  6286.731006
       Master                50568.25912  8168.832659  5579.099207

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

In [63]:
df["Effective To Date"] = pd.to_datetime(df["Effective To Date"], errors="coerce")
df['month'] = pd.to_datetime(df['Effective To Date']).dt.month

df['month'] = pd.to_datetime(df['month'], format='%m').dt.month_name()

C:\Users\eymem\AppData\Local\Temp\ipykernel_10960\2578922024.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Effective To Date"] = pd.to_datetime(df["Effective To Date"], errors="coerce")

In [64]:
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN,February
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN,January
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,February
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,January
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN,January

In [29]:
monthly_policies = (df.groupby(["State", "month", "Policy Type"]).size().unstack(["month", "Policy Type"], fill_value=0))
monthly_policies

month             February                                   January  \
Policy Type Corporate Auto Personal Auto Special Auto Corporate Auto
State
Arizona                167           722           40            214
California             374          1203           57            461
Nevada                  99           334            9            120
Oregon                 287           989           68            305
Washington              89           319           17             86

month
Policy Type Personal Auto Special Auto
State
Arizona               747           47
California           1391           66
Nevada                405           26
Oregon               1191           69
Washington            363           14

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

In [65]:
states = (df["State"].value_counts().head(3).index)
df_top = df[df["State"].isin(states)]
top_monthly_policies = (df_top.groupby(["State", "month"]).size().unstack(fill_value=0))
top_monthly_policies

month       February  January
State
Arizona          929     1008
California      1634     1918
Oregon          1344     1565

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [67]:
df.groupby("Response")['Sales Channel'].count()

Response
No     8813
Yes    1466
Name: Sales Channel, dtype: int64

In [ ]:
marketing_channel = (df.groupby(["Response", "Sales Channel"]).size().unstack(fill_value=0))
marketing_channel

Sales Channel  Agent  Branch  Call Center   Web
Response
No              3148    2539         1792  1334
Yes              742     326          221   177

In [73]:
marketing_channel = marketing_channel.reset_index()
melted = marketing_channel.melt(id_vars="Response", var_name="Sales Channel", value_name="Channel")
melted

  Response Sales Channel  Channel
0       No         Agent     3148
1      Yes         Agent      742
2       No        Branch     2539
3      Yes        Branch      326
4       No   Call Center     1792
5      Yes   Call Center      221
6       No           Web     1334
7      Yes           Web      177